checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
        - vendor/*
tools:
    php_code_sniffer:
      config:
        standard: "PSR2"
    php_cs_fixer: true
    sensiolabs_security_checker: true
    external_code_coverage: true
