language: php

sudo: required

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover coverage.clover"; else PHPUNIT_FLAGS=""; fi

script:
  - phpunit --coverage-text
  - if [ $TRAVIS_PHP_VERSION != '5.3.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./bin/src/ ./tests/; fi

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi