language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - /home/travis/.phpenv/versions/5.3.3/bin/composer self-update

script:
  - phpunit --configuration phpunit.xml.dist
  - ./vendor/bin/phpcs --standard=PSR2 ./bin/src/ ./tests/